name: CI

on: [push]

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v1
    - name: ssh deploy
      uses: appleboy/ssh-action@master
      with:
            host: ${{ secrets.SCSHARK_HOST }}
            username: ${{ secrets.SCSHARK_USER }}
            password: ${{ secrets.SCSHARK_PASSWORD }}
            debug: true
            script: whoami
                    ll
