name: CI

on: [push]

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v1
    - name: ssh deploy
      uses: easingthemes/ssh-deploy@v2.0.7
      env:
            SSH_PRIVATE_KEY: ${{ secrets.SCSHARK_SSH_KEY }}
            SOURCE: "dist/"
            REMOTE_HOST: ${{ secrets.SCSHARK_HOST }}
            REMOTE_USER: ${{ secrets.SCSHARK_USER }}
            TARGET: ${{ secrets.SCSHARK_TARGET }}

