name: CI

on: [push]

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v1
    - name: ssh deploy
      uses: appleboy/ssh-action@master
      env:
            host: ${{ secrets.SCSHARK_HOST }}
            username: ${{ secrets.SCSHARK_USER }}
            key: ${{ secrets.SCSHARK_SSH_KEY }}
            script: whoami
